### ISSUE TITLE
Julia Schultz API lab

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/fun_with_apis#14]
https://github.com/jschultz21/APILAB

_question_ based on today's review, I feel like I could use a forEach on line 48 instead of a for loop, but when I tried it I ran into some issues because i need the i variable to produce my variables imgUrl, artistName and artistPageUrl. 
complete: 4
comfort: 3

**Comment by RobertAKARobin** [comment]
You can! It'd be:

``` js
response.artists.forEach(function(artist){
  // do stuff with artist here, in place of `response.artists[i]`
});
```

My only beef with your code is that the `relatedArtists` function is declared inside an event. In most cases you should declare functions in the root level of your app -- that is, just inside `$(document).ready`.

✅
