### ISSUE TITLE
Dave Corderman API Lab

### ISSUE THREAD

**Issue by dcordz** [ga-wdi-exercises/fun_with_apis#15]
Used the weather underground API and everything worked fine offline but once I pushed it to my github personal page I got an error: This request has been blocked; the content must be served over HTTPS. Is there something I need to change in the ajax call? I'd look this up on google before submitting but it's 8:40AM - not enough time

GH Personal Page - https://dcordz.github.io/GA_Week_4_API_Lab/
Repo - https://github.com/dcordz/GA_Week_4_API_Lab

Comfort - 4/5
Completeness - 4/5

**Comment by dcordz** [comment]
And never mind, that was an easy/dumb fix, changed the URL from http://... to https://... duh...

**Comment by amaseda** [comment]
:+1: Great job with is. All the elements on the page seemed to stack on top of each other for me but that's something I'm sure you could solve with a little CSS magic. Let me know if you need any help with that.
