### ISSUE TITLE
"Fun" with API's

### ISSUE THREAD

**Issue by arthuradams** [ga-wdi-exercises/fun_with_apis#18]
Because I was very very tired Wednesday and Thursday, all i have for "Fun With API's" is a commented up version of slidey-mcshowington, found here. https://github.com/arthuradams/slidey-mcshowington/tree/solution

I intend to do a much better version this weekend and submit it by Monday AM.

**Comment by amaseda** [comment]
Let me know when you submit the update version. Happy to take a look.
