### ISSUE TITLE
James Hughes API Lab

### ISSUE THREAD

**Issue by jhugheswebdev** [ga-wdi-exercises/fun_with_apis#19]
I was trying to get the movie search API to specifically only search "Denzel Washington" movies, but couldn't figure out how to limit the parameters to only search that.

Repo - [https://github.com/jameshughesmagnif/-James-Hughes-API-LAB]

Comfort - 4/5
Completeness - 3.5/5

**Comment by jshawl** [comment]
👍 Nice job on this assignment! The searching by actor seems to be a limitation of the API. Also, remember to clear the HTML before Appending so user's can "reset" their search
