### ISSUE TITLE
API homework

### ISSUE THREAD

**Issue by jaredarkin** [ga-wdi-exercises/fun_with_apis#2]
comfort_level: 4
completeness: 5

https://github.com/arkinjb/soundcloud_api
Searches sound cloud's api and embeds 5 songs that match the search term

Didn't have any trouble getting the info from the API. However, I couldn't use sound cloud's API wrapper (which looked really helpful and easy and would have cut down on the code a lot) because I was opening the index file locally. I couldn't figure out how to change my request in their API wrapper to include http:// instead of file:// - the request was trying to go to file://soundcloudapi.com 

Also, there is a noticeable delay when it's running the ajax requests and embedding the players. Is there a way to tell if the delay is caused by the amount of information I'm requesting or the embedding process?

**Comment by jshawl** [comment]
Awesome job on this hw!! 

re: opening the file locally, you can use `$ python -m SimpleHTTPServer` and view on port 8000.

re: the noticeable delay. This is totally soundcloud's fault. I opened up the network dev tools, and can watch the initial api call, and then all the subsequent calls from the embedded soundcloud player.

I recommend showing some sort of loading gif to reduce the feeling of the delay, but great job on this hw!
