### ISSUE TITLE
Vete al Grano / Need Bowls Now

### ISSUE THREAD

**Issue by wombatdev** [ga-wdi-exercises/fun_with_apis#20]
Sorry for late delivery. Moved last night and don't have internet at either place. Planned to arrive before 9 but failed. https://github.com/wombatdev/vetealgrano

Index/style/script are all for Vete al Grano/YouTube API; ramen files are my failed attempt to use Yelp API.

```
Comfort: 4/5
Completeness: 4/5
```

**Comment by amaseda** [comment]
:+1:

I don't have many comments to add here, other than when referencing a response -- whether it's a success or failure -- make sure to pass that in as an argument to the callback.

Wish I could say more about setting up OAuth on the front-end but, as we've discussed, that's not something you would do. Definitely give it another shot once we dive into Rails.
