### ISSUE TITLE
fun with APIs

### ISSUE THREAD

**Issue by AT89** [ga-wdi-exercises/fun_with_apis#9]
Reddit img API
4/5 comfort level - alot of resources online, so alot to look for, probably can sole my problems with more time but I figured out what they were

?/5 completeness - it does the basics but only returns first page.. It was the end of the day at 5 so I called it a day.

https://github.com/AT89/API_FUN

**Comment by RobertAKARobin** [comment]
Great job on tidying up your code, Anh! Keep it up!

✅
